# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.12

repos:
## GENERAL
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-toml
    -   id: check-yaml
        args: ["--unsafe"]
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: no-commit-to-branch
    -   id: pretty-format-json
        args: ["--autofix", --no-sort-keys, --no-ensure-ascii]

## TOML
-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.13.0
    hooks:
      - id: pretty-format-toml
        args: [--autofix]
        files: pyproject.toml

## PYTHON
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
    -   id: ruff-format

-   repo: https://github.com/hadolint/hadolint
    rev: v2.13.0-beta
    hooks:
      - id: hadolint-docker
        args: ["--ignore=DL3013"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        additional_dependencies:
            [
                "types-aiofiles",
                "pydantic",
                "pydantic-settings",
                "sqlalchemy"
            ]

-   repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        args: ["--disable=W,C,R,E", "-j", "0", "-rn", "-sn"]
        language: system
        types: [python]

      - id: bandit
        name: bandit
        description: "Bandit is a tool for finding common security issues in Python code"
        entry: bandit
        args: ["-q", "-lll", "-x", "*_test.py,./contrib/,./.venv/,./tests/", "-r", "."]
        language: system
        types: [python]
