# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.12

repos:
## GENERAL
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-toml
    -   id: check-yaml
        args: ["--unsafe"]
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: no-commit-to-branch
    -   id: pretty-format-json
        args: ["--autofix", --no-sort-keys, --no-ensure-ascii]

## TOML
-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.13.0
    hooks:
      - id: pretty-format-toml
        args: [--autofix]
        files: pyproject.toml

## PYTHON
-   repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]

-   repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variable",
          ]

-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        exclude: contrib
        args: ["--ignore=E266,W503,E203,E501,W605"]

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.2
    hooks:
    -   id: ruff
        exclude: migrations/
        args:
        - --fix
    -   id: ruff-format

-   repo: https://github.com/hadolint/hadolint
    rev: v2.13.0-beta
    hooks:
      - id: hadolint-docker
        args: ["--ignore=DL3013"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        exclude: migrations/
        additional_dependencies:
            [
                "redis==4.5.1",
                "types-redis==4.6.0",
                "types-ujson==5.9.0",
            ]


-   repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: bash -c 'pylint --disable=W,C,R,E -j 0 -rn -sn src/'
        language: system
        files: '.*\.py'

      - id: bandit
        name: bandit
        description: "Bandit is a tool for finding common security issues in Python code"
        entry: bash -c 'bandit -q -lll -x '*_test.py,./contrib/,./.venv/' -r .'
        language: system
        files: '.*\.py'